const { normalizeKey } = require("./utils");
const CLASSES = {
  knight: {
    name: "Knight",
    emoji: "⚔️",
    style: "Frontline fighter",
    strengths: "Armor, stamina, sustained melee",
    weaknesses: "Magic and ranged pressure",
    base: {
      maxHp: 130,
      maxMp: 35,
      maxStamina: 120,
      strength: 18,
      defense: 16,
      agility: 10,
      intelligence: 6,
      vitality: 16,
      luck: 8,
    },
    skills: ["power_strike", "iron_wall"],
    subclasses: ["warden", "royal_knight"],
  },
  bloodreaver: {
    name: "Bloodreaver",
    emoji: "🩸",
    style: "High-risk damage dealer",
    strengths: "Critical damage and execution",
    weaknesses: "Low defense and resource efficiency",
    base: {
      maxHp: 105,
      maxMp: 30,
      maxStamina: 115,
      strength: 24,
      defense: 9,
      agility: 13,
      intelligence: 5,
      vitality: 11,
      luck: 12,
    },
    skills: ["blood_rush", "execution"],
    subclasses: ["berserker", "reaver_lord"],
  },
  arcanist: {
    name: "Arcanist",
    emoji: "🧙",
    style: "Magic and area control",
    strengths: "High spell damage and utility",
    weaknesses: "Fragile when out of mana",
    base: {
      maxHp: 85,
      maxMp: 120,
      maxStamina: 80,
      strength: 5,
      defense: 8,
      agility: 9,
      intelligence: 25,
      vitality: 8,
      luck: 10,
    },
    skills: ["arcane_bolt", "inferno"],
    subclasses: ["archmage", "voidcaller"],
  },
  wraith: {
    name: "Wraith",
    emoji: "🗡️",
    style: "Stealth and assassination",
    strengths: "Dodge, critical hits, infiltration",
    weaknesses: "Long fights and heavy armor",
    base: {
      maxHp: 92,
      maxMp: 55,
      maxStamina: 110,
      strength: 19,
      defense: 10,
      agility: 23,
      intelligence: 9,
      vitality: 9,
      luck: 16,
    },
    skills: ["shadow_strike", "vanish"],
    subclasses: ["nightblade", "shadow_lord"],
  },
  paladin: {
    name: "Paladin",
    emoji: "🛡️",
    style: "Defense and support",
    strengths: "Healing, armor, protection",
    weaknesses: "Slow damage tempo",
    base: {
      maxHp: 145,
      maxMp: 70,
      maxStamina: 100,
      strength: 14,
      defense: 22,
      agility: 6,
      intelligence: 12,
      vitality: 20,
      luck: 7,
    },
    skills: ["holy_strike", "divine_guard"],
    subclasses: ["templar", "sunwarden"],
  },
  ranger: {
    name: "Ranger",
    emoji: "🏹",
    style: "Ranged damage and scouting",
    strengths: "Accuracy, movement, resource gathering",
    weaknesses: "Close-range pressure",
    base: {
      maxHp: 100,
      maxMp: 45,
      maxStamina: 125,
      strength: 17,
      defense: 11,
      agility: 21,
      intelligence: 10,
      vitality: 10,
      luck: 15,
    },
    skills: ["aimed_shot", "hunter_trap"],
    subclasses: ["ranger_lord", "beastwarden"],
  },
  assassin: {
    name: "Assassin",
    emoji: "☠️",
    style: "Burst damage and infiltration",
    strengths: "Critical hits and first strikes",
    weaknesses: "Defense and prolonged battles",
    base: {
      maxHp: 88,
      maxMp: 45,
      maxStamina: 130,
      strength: 22,
      defense: 8,
      agility: 25,
      intelligence: 8,
      vitality: 8,
      luck: 19,
    },
    skills: ["ambush", "poison_blade"],
    subclasses: ["master_assassin", "shadow_lord"],
  },
};
const SKILLS = {
  power_strike: {
    name: "Power Strike",
    emoji: "⚔️",
    cost: 12,
    stamina: 14,
    multiplier: 1.8,
    effect: "damage",
  },
  iron_wall: {
    name: "Iron Wall",
    emoji: "🛡️",
    cost: 8,
    stamina: 8,
    multiplier: 0,
    effect: "guard",
  },
  blood_rush: {
    name: "Blood Rush",
    emoji: "🩸",
    cost: 10,
    stamina: 18,
    multiplier: 2.1,
    effect: "damage",
  },
  execution: {
    name: "Execution",
    emoji: "💀",
    cost: 20,
    stamina: 24,
    multiplier: 2.8,
    effect: "execute",
  },
  arcane_bolt: {
    name: "Arcane Bolt",
    emoji: "🔷",
    cost: 22,
    stamina: 4,
    multiplier: 2.2,
    effect: "magic",
  },
  inferno: {
    name: "Inferno",
    emoji: "🔥",
    cost: 45,
    stamina: 8,
    multiplier: 3.3,
    effect: "magic",
  },
  shadow_strike: {
    name: "Shadow Strike",
    emoji: "🌑",
    cost: 15,
    stamina: 12,
    multiplier: 2.4,
    effect: "critical",
  },
  vanish: {
    name: "Vanish",
    emoji: "💨",
    cost: 12,
    stamina: 15,
    multiplier: 0,
    effect: "dodge",
  },
  holy_strike: {
    name: "Holy Strike",
    emoji: "✨",
    cost: 18,
    stamina: 10,
    multiplier: 1.7,
    effect: "heal_damage",
  },
  divine_guard: {
    name: "Divine Guard",
    emoji: "🛡️",
    cost: 25,
    stamina: 8,
    multiplier: 0,
    effect: "guard_heal",
  },
  aimed_shot: {
    name: "Aimed Shot",
    emoji: "🎯",
    cost: 14,
    stamina: 12,
    multiplier: 2.3,
    effect: "critical",
  },
  hunter_trap: {
    name: "Hunter Trap",
    emoji: "🪤",
    cost: 12,
    stamina: 10,
    multiplier: 1.5,
    effect: "stun",
  },
  ambush: {
    name: "Ambush",
    emoji: "🗡️",
    cost: 18,
    stamina: 16,
    multiplier: 2.7,
    effect: "critical",
  },
  poison_blade: {
    name: "Poison Blade",
    emoji: "☠️",
    cost: 15,
    stamina: 12,
    multiplier: 2,
    effect: "poison",
  },
};
function getClass(value) {
  return CLASSES[normalizeKey(value)] || CLASSES.knight;
}
function getClassKey(value) {
  const key = normalizeKey(value);
  return CLASSES[key] ? key : "knight";
}
function getSkill(value) {
  return SKILLS[normalizeKey(value)] || null;
}
function getSkillsForClass(value) {
  const definition = getClass(value);
  return definition.skills.map((skillId) => ({
    id: skillId,
    ...SKILLS[skillId],
  }));
}
module.exports = {
  CLASSES,
  SKILLS,
  getClass,
  getClassKey,
  getSkill,
  getSkillsForClass,
};
