const ITEMS = {
  minor_potion: {
    id: "minor_potion",
    name: "Minor Healing Potion",
    emoji: "🧪",
    type: "consumable",
    rarity: "Common",
    value: 100,
    effect: { hp: 35 },
    description: "Restores 35 HP during combat.",
  },
  mana_potion: {
    id: "mana_potion",
    name: "Mana Potion",
    emoji: "🔷",
    type: "consumable",
    rarity: "Common",
    value: 120,
    effect: { mp: 30 },
    description: "Restores 30 MP during combat.",
  },
  iron_sword: {
    id: "iron_sword",
    name: "Iron Sword",
    emoji: "⚔️",
    type: "weapon",
    rarity: "Common",
    value: 250,
    stats: { strength: 5 },
    description: "A dependable starter weapon.",
  },
  ranger_bow: {
    id: "ranger_bow",
    name: "Ranger Bow",
    emoji: "🏹",
    type: "weapon",
    rarity: "Uncommon",
    value: 600,
    stats: { agility: 7, luck: 2 },
    description: "A light bow built for accurate shots.",
  },
  apprentice_robe: {
    id: "apprentice_robe",
    name: "Apprentice Robe",
    emoji: "🧥",
    type: "armor",
    rarity: "Common",
    value: 300,
    stats: { intelligence: 5, maxMp: 15 },
    description: "A simple robe with a little arcane protection.",
  },
  moonleaf: {
    id: "moonleaf",
    name: "Moonleaf",
    emoji: "🌿",
    type: "material",
    rarity: "Uncommon",
    value: 40,
    description: "A cool herb used in crafting.",
  },
  iron: {
    id: "iron",
    name: "Iron",
    emoji: "⛓️",
    type: "material",
    rarity: "Common",
    value: 25,
    description: "Refined metal for weapons and buildings.",
  },
  void_crystal: {
    id: "void_crystal",
    name: "Void Crystal",
    emoji: "💎",
    type: "material",
    rarity: "Epic",
    value: 500,
    description: "A dangerous crystal from the Abyss.",
  },
};
function getItem(itemId) {
  return ITEMS[String(itemId || "").trim().toLowerCase()] || null;
}
module.exports = {
  ITEMS,
  getItem,
};
